### PR TITLE
removing bug of font size of writing page

### LINKED ISSUE #36: Writing page font styling bug
image

### PR DESCRIPTION
**Pull request by harshsinghcs**
I solved a bug styling in the writing page and also added some CSS

Before:-
image

after:-
image

### CODE REVIEW

**Comment by harshsinghcs** [comment]
#36

**Comment by harshsinghcs** [comment]
kindly accept this under hacktoberfest

**Comment by harshsinghcs** [comment]
Writing page font styling bug #36

**Review by amrit03b — APPROVED** [review]

**Comment by amrit03b** [comment]
> Writing page font styling bug #36

Great.

**Pull request merged**
